name: get_ui_state_package
description: >
  A lightweight Flutter package using GetX to manage common UI states like loading, error, and success.
version: 0.0.5

homepage: https://github.com/sourabhappdev/get_ui_state_package
repository: https://github.com/sourabhappdev/get_ui_state_package
issue_tracker: https://github.com/sourabhappdev/get_ui_state_package/issues

environment:
  sdk: ">=3.7.2 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  get: ^4.7.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1 # Latest compatible stable version

flutter:
  uses-material-design: true
